version: "3.9"

services:
  web:
    image: ponderful-1.0.0
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - /mnt/e/Maryam/Ponderful/Percent_changes_CombinedCC_LU:/app/raster_files
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASS="postgres"
      - POSTGRES_DBNAME="ponderful"
      
    ports:
      - "${DB_HOST_PORT}:5434"

volumes:
  postgres_data:
