# Generated by Django 4.0 on 2023-08-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
    ]
