# Generated by Django 4.0 on 2023-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Criteria Name')),
                ('unit_of_measure', models.CharField(max_length=255, verbose_name='Unit of Measure')),
            ],
        ),
    ]
