# Generated by Django 4.0 on 2023-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default='none', max_length=255, verbose_name='Organization'),
        ),
    ]
