# Generated by Django 4.0 on 2023-08-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0002_customuser_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
    ]
