# Generated by Django 4.0 on 2023-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponderful_mcda', '0002_delete_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('obs_type', models.CharField(choices=[('tree', 'Tree'), ('bird', 'Bird'), ('flower', 'Flower'), ('butterfly', 'Butterfly')], default='none', max_length=255)),
            ],
        ),
    ]
