# Generated by Django 4.0 on 2023-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
    ]
