# Generated by Django 4.0 on 2023-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0003_criteria_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Study Area Name'),
        ),
    ]
