# Generated by Django 4.0 on 2023-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0004_studyarea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Study Area Name'),
        ),
    ]
