# Generated by Django 4.0 on 2023-12-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0007_criteria_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='satisfaction_threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_min', models.FloatField(verbose_name='minimum satisfaction threshold')),
                ('threshold_max', models.FloatField(verbose_name='maximum satisfaction threshold')),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.criteria')),
                ('study_area', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.studyarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.customuser')),
            ],
        ),
    ]
