# Generated by Django 4.0 on 2023-12-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0010_alter_criteria_params_weight_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria_params',
            old_name='criteria_id',
            new_name='criteria',
        ),
    ]
