# Generated by Django 4.0 on 2024-01-17 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0011_rename_criteria_id_criteria_params_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_params',
            name='weight_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=2, verbose_name='Weight Range'),
        ),
    ]
