# Generated by Django 4.0 on 2024-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0012_alter_criteria_params_weight_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria_params',
            name='weight_percentage',
            field=models.FloatField(default=100, verbose_name='Weight'),
        ),
    ]
