# Generated by Django 4.0 on 2024-02-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0018_analysisrun_analysis_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria_params',
            name='analysis_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.analysisrun'),
            preserve_default=False,
        ),
    ]
