# Generated by Django 4.0 on 2024-02-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0020_alternatives_params_analysis_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sustainability', 'Sustainability'), ('Regional rivalry', 'Regional rivalry'), ('Fossil-fueled development', 'Fossil-fueled development')], max_length=255, verbose_name='Climate Change Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='scenario_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.analysisrun')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.scenario')),
            ],
        ),
    ]
