# Generated by Django 4.0 on 2024-02-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0023_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
