# Generated by Django 4.0 on 2024-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0029_mcda_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(choices=[('Sustainability', 'Sustainability'), ('Regional rivalry', 'Regional rivalry'), ('Fossil-fueled development', 'Fossil-fueled development'), ('Without land use change', 'Without land use change')], max_length=255, verbose_name='Climate Change Scenario'),
        ),
    ]
