# Generated by Django 4.0 on 2024-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0030_alter_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
