# Generated by Django 4.0 on 2024-04-16 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0033_alter_criteria_params_rank_alter_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Criteria Name'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Criteria Name'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='unit_of_measure_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='unit_of_measure_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.action_types', verbose_name='NBS implementation type'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Maximum number of ponds'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Minimum number of ponds'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_size',
            field=models.CharField(choices=[('small', 'Small'), ('average', 'Average'), ('big', 'Big')], default='none', max_length=255, verbose_name='Pond Size'),
        ),
        migrations.AlterField(
            model_name='criteria_params',
            name='rank',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='scenario_user',
            name='scenario_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.scenario', verbose_name='Scenario Type'),
        ),
    ]
