# Generated by Django 4.0 on 2024-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0034_criteria_name_en_criteria_name_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_params',
            name='rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(choices=[('Utilisation des sols : SSP1, Changement climatique : SSP1', 'Land Use: SSP1, Climate Change: SSP1'), ('Utilisation des sols : SSP3, Changement climatique : SSP3', 'Land Use: SSP3, Climate Change: SSP3'), ('Utilisation des sols : SSP5, Changement climatique : SSP5', 'Land Use: SSP5, Climate Change: SSP5'), ('Utilisation des sols : Pas de changement, changement climatique : SSP1', 'Land Use: No Change, Climate Change: SSP1'), ('Utilisation des sols : Pas de changement, changement climatique : SSP3', 'Land Use: No Change, Climate Change: SSP3'), ('Utilisation des sols : Pas de changement, changement climatique : SSP5', 'Land Use: No Change, Climate Change: SSP5'), ('Utilisation des sols : Pas de changement, changement climatique : Pas de changement', 'Land Use: No Change, Climate Change: No Change')], max_length=255, verbose_name='Climate Change Scenario'),
        ),
    ]
