# Generated by Django 4.0 on 2024-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0037_alter_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
