# Generated by Django 4.0 on 2024-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0038_scenario_description_en_scenario_description_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='climate',
            field=models.CharField(blank=True, choices=[('No Change', 'No Change'), ('Slight', 'Slight'), ('Moderate', 'Moderate'), ('Strong', 'Strong')], max_length=255, null=True, verbose_name='Climate Change'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='landuse',
            field=models.CharField(blank=True, choices=[('No Change', 'No Change'), ('Slight', 'Slight'), ('Moderate', 'Moderate'), ('Strong', 'Strong')], max_length=255, null=True, verbose_name='Land Use'),
        ),
    ]
