# Generated by Django 4.0 on 2024-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0040_studyarea_total_pond_studyarea_trophic_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='trophic_state',
            field=models.CharField(blank=True, choices=[('oligotrophe', 'Oligotrophe'), ('mesotrophe', 'Mesotrophe'), ('eutrophe', 'Eutrophe'), ('hypertrophe', 'Hypertrophe'), ('hautement hypertrophe', 'Hautement hypertrophe'), ('I do not know', 'I do not know')], max_length=255, verbose_name='Trophic Status'),
        ),
    ]
