# Generated by Django 4.0 on 2024-09-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0042_studyarea_avg_amphi_ssp1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='avg_amphi_ssp2',
            field=models.FloatField(blank=True, null=True, verbose_name='average_amph_ssp2'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='avg_amphi_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='average_amph_ssp3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='co2_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='co2_ssp1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='co2_ssp2',
            field=models.FloatField(blank=True, null=True, verbose_name='co2_ssp2'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='co2_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='co2_ssp3'),
        ),
    ]
