# Generated by Django 4.0 on 2024-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0044_rename_avg_amphi_ssp1_studyarea_amphibia_ssp1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='Amphibia_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia SSP1'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='Amphibia_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia SSP3'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='Amphibia_ssp5',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia SSP5'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='CO2_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 SSP1'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='CO2_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 SSP3'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='CO2_ssp5',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 SSP5'),
        ),
    ]
