# Generated by Django 4.0 on 2024-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0046_amphi_accumulation_macrophyte_accumulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_types',
            name='name',
            field=models.CharField(choices=[('Creation', 'Creation'), ('Water Quality Management', 'Water Quality Management'), ('No action', 'No action')], max_length=255, verbose_name='Action Name'),
        ),
    ]
