# Generated by Django 4.0 on 2024-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0047_alter_action_types_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='Amphibia_ssp1_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia LUOnly SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Amphibia_ssp3_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia LUOnly SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Amphibia_ssp5_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Amphibia LUOnly SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='CO2_ssp1_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 LUOnly SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='CO2_ssp3_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 LUOnly SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='CO2_ssp5_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2 LUOnly SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp1_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG LUOnly SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp3_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG LUOnly SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp5',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='GHG_ssp5_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='GHG LUOnly SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='MI SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp1_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='MI LUOnly SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='MI SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp3_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='MI LUOnly SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp5',
            field=models.FloatField(blank=True, null=True, verbose_name='MI SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='MI_ssp5_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='MI LUOnly SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp1',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp1_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte LUOnly SSP1'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp3',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp3_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte LUOnly SSP3'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp5',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte SSP5'),
        ),
        migrations.AddField(
            model_name='studyarea',
            name='Macrophyte_ssp5_LU',
            field=models.FloatField(blank=True, null=True, verbose_name='Macrophyte LUOnly SSP5'),
        ),
    ]
