# Generated by Django 4.0 on 2024-09-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0048_studyarea_amphibia_ssp1_lu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAreaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_value', models.FloatField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.criteria')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.scenario')),
                ('study_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ponderful_mcda.studyarea')),
            ],
        ),
    ]
