# Generated by Django 4.0 on 2024-10-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0053_trophicstate_rank_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophicstate',
            old_name='rank_2',
            new_name='degree',
        ),
    ]
