# Generated by Django 4.0 on 2024-10-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0054_rename_rank_2_trophicstate_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTrophicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.criteria')),
                ('trophic_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.trophicstate')),
            ],
        ),
    ]
