# Generated by Django 4.0 on 2024-10-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0055_indicatortrophicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='accumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('sp_richness', models.IntegerField()),
                ('pond_num', models.IntegerField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.criteria')),
            ],
        ),
    ]
