# Generated by Django 4.0 on 2024-10-01 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0057_migrate_accumulation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternatives_params',
            name='pond_size',
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Maximum number of ponds'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Minimum number of ponds'),
        ),
    ]
