# Generated by Django 4.0 on 2024-10-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0058_remove_alternatives_params_pond_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophicstate',
            name='trophic_state',
            field=models.CharField(blank=True, choices=[('unknown', 'I do not know'), ('highly hypertrophic', 'Highly Hypertrophic'), ('hypertrophic', 'Hypertrophic'), ('eutrophic', 'Eutrophic'), ('mesotrophic', 'Mesotrophic'), ('oligotrophic', 'Oligotrophic')], max_length=50, verbose_name='Trophic State'),
        ),
        migrations.CreateModel(
            name='satisfaction_objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_min', models.FloatField(verbose_name='Minimum satisfying objective')),
                ('threshold_max', models.FloatField(verbose_name='Fully satisfying objective')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.analysisrun')),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.criteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponderful_mcda.customuser')),
            ],
        ),
    ]
