# Generated by Django 4.0 on 2024-10-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0059_alter_trophicstate_trophic_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria_params',
            name='threshold_max',
            field=models.FloatField(blank=True, null=True, verbose_name='maximum satisfaction threshold'),
        ),
        migrations.AddField(
            model_name='criteria_params',
            name='threshold_min',
            field=models.FloatField(blank=True, null=True, verbose_name='minimum satisfaction threshold'),
        ),
    ]
