# Generated by Django 4.0 on 2024-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0060_criteria_params_threshold_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria_params',
            name='threshold_max',
            field=models.FloatField(default=0, verbose_name='maximum satisfaction threshold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criteria_params',
            name='threshold_min',
            field=models.FloatField(default=0, verbose_name='minimum satisfaction threshold'),
            preserve_default=False,
        ),
    ]
