# Generated by Django 4.0 on 2024-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0064_criteria_ncp'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='s_threshold_max',
            field=models.FloatField(blank=True, null=True, verbose_name='default maximum satisfaction threshold'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='s_threshold_min',
            field=models.FloatField(blank=True, null=True, verbose_name='default minimum satisfaction threshold'),
        ),
    ]
