# Generated by Django 4.0 on 2024-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0065_criteria_s_threshold_max_criteria_s_threshold_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_types',
            name='name',
            field=models.CharField(choices=[('Creation of new ponds', 'Creation of new ponds'), ('Management of Water Quality', 'Management of Water Quality'), ('No action', 'No action')], max_length=255, verbose_name='Action Name'),
        ),
    ]
