# Generated by Django 4.0 on 2024-11-11 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0067_alter_action_types_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum number of ponds'),
        ),
        migrations.AlterField(
            model_name='alternatives_params',
            name='pond_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum number of ponds'),
        ),
        migrations.AlterField(
            model_name='trophicstate',
            name='trophic_state',
            field=models.CharField(blank=True, choices=[('unknown', 'I do not know'), ('highly hypertrophic', 'Highly Hypertrophic'), ('hypertrophic', 'Hypertrophic'), ('eutrophic', 'Eutrophic'), ('oligo-mesotrophic', 'Oligo-mesotrophic')], max_length=50, verbose_name='Trophic State'),
        ),
    ]
