# Generated by Django 4.0 on 2024-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0068_alter_alternatives_params_pond_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
