# Generated by Django 4.0 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponderful_mcda', '0069_criteria_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='handbook_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Handbook page'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='objective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='total_pond',
            field=models.IntegerField(default=0, verbose_name='Total number of existing ponds'),
            preserve_default=False,
        ),
    ]
